cheat-library/cheat-library.vcxproj
cheat-library/cheat-library.vcxproj.filters
cheat-library/src/appdata/il2cpp-functions.h
cheat-library/src/appdata/il2cpp-types.h
cheat-library/src/user/cheat/cheat.cpp
cheat-library/src/user/cheat/player/NoCD.cpp
cheat-library/src/user/cheat/player/NoCD.h
cheat-library/src/user/cheat/player/NoClip.cpp
cheat-library/src/user/cheat/player/NoClip.h
cheat-library/src/user/cheat/visuals/ShowChestIndicator.cpp
cheat-library/src/user/cheat/visuals/ShowChestIndicator.h
cheat-library/src/user/cheat/world/AutoCook.cpp
cheat-library/src/user/cheat/world/AutoCook.h

Update CD Reduce,  Based on changing the timer
Update NoClip, Added on / off player animation (requested in discord)
Add Show Chest, Show chests c using game mechanics, there is a small bug, I will fix it later (not critical)
Add Auto Cook, You can improve this function, I don't really want to bother with it right now

upd ryujin | 2.6

---

cheat-library/src/user/cheat/esp/ESP.cpp
cheat-library/src/user/cheat/esp/ESP.h
cheat-library/src/user/cheat/esp/ESPRender.cpp

tracer be in middle of screen instead of avatar feet

tracer middle

---

cheat-library/src/user/cheat/player/RapidFire.cpp

Ores, geograna, and rock piles are now affected by Attack Modifiers (both multi-hit and multi-target). Fixed multi-target to affect animals as well. Separated into a function for now so it's easier to modify than using a filter.

Added ore and some other items to Attack Modifiers.

---

cheat-base/src/cheat-base/cheat/CheatManagerBase.cpp

Update Cheat Name

---

cheat-library/src/user/cheat/esp/ESP.cpp
cheat-library/src/user/cheat/game/filters.cpp
cheat-library/src/user/cheat/game/filters.h

because im to lazy to remember the precise location of them

added Dunlins Tooth to the ESP

---

cheat-library/src/user/cheat/esp/ESP.cpp
cheat-library/src/user/cheat/game/filters.cpp
cheat-library/src/user/cheat/game/filters.h

added relay stones to the ESP

---

cheat-library/cheat-library.vcxproj
cheat-library/cheat-library.vcxproj.filters
cheat-library/src/appdata/il2cpp-functions.h
cheat-library/src/appdata/il2cpp-types.h
cheat-library/src/user/cheat/cheat.cpp
cheat-library/src/user/cheat/player/GodMode.cpp
cheat-library/src/user/cheat/player/GodMode.h
cheat-library/src/user/cheat/visuals/EnablePeaking.cpp
cheat-library/src/user/cheat/visuals/EnablePeaking.h
cheat-library/src/user/cheat/world/MusicEvent.cpp
cheat-library/src/user/cheat/world/MusicEvent.h

<h1>MusicEvent</h1>
**How to use:**
- Need to hit 1 keynote to work
**What to improve:**
- Auto press all keynotes
- Auto finish (?)
<details>
<summary>Result</summary>
</details>
<h1>EnablePeaking</h1>
yes!
<h1>Alternative God Mode</h1>
- Hooking ``FireBeingHitEvent``
- Added Environmental Damage immunity. Special thanks to @34736384
- Fix #60  &  Fix #39 
<details>
<summary>Demo</summary>
<br>
<a href="https://imgur.com/a/iAnyzBE">Video</a>
</details>

Temporary MusicEvent cheese, Added Enable Peaking, Added Alternative God Mode

---

cheat-library/src/user/cheat/esp/ESP.cpp
cheat-library/src/user/cheat/game/filters.cpp
cheat-library/src/user/cheat/game/filters.h
cheat-library/src/user/cheat/imap/InteractiveMap.cpp

Fix Starsilver 'filter not found' in Interactive Map

---

cheat-library/src/user/cheat/world/AutoLoot.cpp
cheat-library/src/user/cheat/world/AutoLoot.h

<details>
<summary>Preview</summary>
</details>

Add pickup filter for Auto Pickup

---

cheat-library/src/user/cheat/teleport/CustomTeleports.cpp

fix #153, change iteration method for unchecking "All"

---

cheat-library/cheat-library.vcxproj
cheat-library/cheat-library.vcxproj.filters
cheat-library/src/appdata/il2cpp-functions.h
cheat-library/src/appdata/il2cpp-types.h
cheat-library/src/user/cheat/cheat.cpp
cheat-library/src/user/cheat/visuals/TextureChanger.cpp
cheat-library/src/user/cheat/visuals/TextureChanger.h

Character Texture Change:
Free Texture: https://disk.yandex.ru/d/VMrNWpCIHC2JJA

Texture Changer

---

cheat-library/cheat-library.vcxproj
cheat-library/cheat-library.vcxproj.filters
cheat-library/src/user/cheat/cheat.cpp
cheat-library/src/user/cheat/world/AutoSeelie.cpp
cheat-library/src/user/cheat/world/AutoSeelie.h

#172 
Don't work with electro seelies atm
Preview:
https://user-images.githubusercontent.com/84017229/175811691-ce6423d5-e0a5-4eb8-bb1f-d68360c6eaf0.mp4

Auto follow seelie

---

cheat-library/src/user/cheat/visuals/ProfileChanger.cpp
cheat-library/src/user/cheat/visuals/ProfileChanger.h

WaterMark fix missing "UID"

---

cheat-library/src/user/cheat/imap/InteractiveMap.cpp

https://user-images.githubusercontent.com/48222039/177005135-3a64f9f5-c0c4-4bad-89a6-c5cd442e126c.mp4

added complete points button to interactive map

---

cheat-library/src/user/cheat/imap/InteractiveMap.cpp
cheat-library/src/user/cheat/imap/InteractiveMap.h

Add in-completed options for Interactive Map icon view

---

cheat-library/cheat-library.vcxproj
cheat-library/cheat-library.vcxproj.filters
cheat-library/src/appdata/il2cpp-functions.h
cheat-library/src/user/cheat/cheat.cpp
cheat-library/src/user/cheat/visuals/FreeCamera.cpp
cheat-library/src/user/cheat/visuals/FreeCamera.h

Not fully tested yet but it works fine from what I experienced so far. I don't know cpp so please let me know if I messed things up.

Add free camera

---

cheat-library/src/user/cheat/teleport/CustomTeleports.cpp
cheat-library/src/user/cheat/teleport/CustomTeleports.h

change into table view (it was tree view) and add descriptions to teleports

Better CustomTeleports

---

cheat-library/src/user/cheat/imap/InteractiveMap.cpp

Solve #199 
I'm newbie to ImGui, so if there is existing InputText focus event, feel free to revise

Fix Interactive Map keyboard input bug

---

injector/src/main.cpp

Forge the parent process as "explorer", and support starting the bilibili server through the injector #96

Bilibili&parent process

---

cheat-library/src/appdata/il2cpp-types.h

- fix #246 
- renamed some struc

Fix shuffled protos

---

.github/workflows/main.yml

No need to deal with visual studio anymore😉

Add github auto build

---

cheat-library/src/user/cheat/player/NoClip.cpp
cheat-library/src/user/cheat/player/NoClip.h

Add's options to have Custom HotKeys as well as a Toggle To turn their Usage On/Off

Custom no clip keys add toggle

---

cheat-library/src/user/cheat/esp/ESP.cpp
cheat-library/src/user/cheat/game/filters.cpp

Fixed Incorrect display of all `ESP` names

Hotfix #323

---

cheat-library/src/user/cheat/game/filters.cpp

Maybe some unnecessary types can be filtered out, e.g. "NPC_Others".

Update npc filters

---

cheat-library/cheat-library.vcxproj
cheat-library/cheat-library.vcxproj.filters
cheat-library/src/appdata/il2cpp-functions.h
cheat-library/src/appdata/il2cpp-types.h
cheat-library/src/user/cheat/cheat.cpp
cheat-library/src/user/cheat/misc/WindSeedBypass.cpp
cheat-library/src/user/cheat/misc/WindSeedBypass.h

This patch adds a new feature to block WindSeed & PlayerLuaShellNotify packets. The function offsets are from OSCB 2.8.51

Block WindSeed packets

---

cheat-library/cheat-library.vcxproj
cheat-library/cheat-library.vcxproj.filters
cheat-library/src/appdata/il2cpp-functions.h
cheat-library/src/user/cheat/cheat.cpp
cheat-library/src/user/cheat/game/filters.cpp
cheat-library/src/user/cheat/game/filters.h
cheat-library/src/user/cheat/imap/InteractiveMap.cpp
cheat-library/src/user/cheat/world/CustomWeather.cpp
cheat-library/src/user/cheat/world/CustomWeather.h

1. Custom Weather
2. Lightning target
3. Fix Exception miniMap

Custom Weather & Lightning target & Fix Exception miniMap

---

cheat-library/src/appdata/il2cpp-functions.h
cheat-library/src/appdata/il2cpp-types.h
cheat-library/src/user/cheat/game/filters.cpp
cheat-library/src/user/cheat/game/filters.h
cheat-library/src/user/cheat/player/NoCD.cpp
cheat-library/src/user/cheat/player/RapidFire.cpp

hotfix bug

---

cheat-library/src/user/cheat/teleport/CustomTeleports.cpp

quick fix for #443

---

cheat-library/src/user/cheat/world/AutoCook.cpp
cheat-library/src/user/cheat/world/AutoCook.h

Added a dropdown where user can choose cooking quality from listed qualities (Suspicious, Normal and Delicious).

Improve AutoCook feature

---

cheat-library/src/user/cheat/teleport/CustomTeleports.cpp
cheat-library/src/user/cheat/teleport/CustomTeleports.h

Add teleportation automation on custom teleport

---

cheat-library/src/user/cheat/world/KillAura.cpp
cheat-library/src/user/cheat/world/KillAura.h

Allows players to customize crash damage value

Killaura damage value

---

cheat-library/src/user/cheat/world/AutoLoot.cpp
cheat-library/src/user/cheat/world/AutoLoot.h

Paranoid feature to added certain amount of random delay to autoloot to mimic human tapping

Added setting to add randomise fluctuation delay for autoloot

---

cheat-library/src/appdata/il2cpp-types.h
cheat-library/src/user/cheat/game/filters.cpp

fixed some features

---

cheat-library/src/user/cheat/world/KillAura.cpp
cheat-library/src/user/cheat/world/KillAura.h

let you decide how many times to kill monsters

add percent crash damage  mode

---

cheat-library/src/user/cheat/game/filters.cpp

- Change filter of 2 monster to its correct position

Fix swapped type of RishbolandTiger and ShaggySumpterBeast

---

cheat-library/cheat-library.vcxproj
cheat-library/cheat-library.vcxproj.filters
cheat-library/src/appdata/il2cpp-functions.h
cheat-library/src/appdata/il2cpp-types.h
cheat-library/src/user/cheat/cheat.cpp
cheat-library/src/user/cheat/world/OpenTeamImmediately.cpp
cheat-library/src/user/cheat/world/OpenTeamImmediately.h

add open team immediately

---

cheat-library/src/user/cheat/game/Chest.cpp

Adds the Sumeru Crude Chest to esp

---

cheat-library/src/user/cheat/game/filters.cpp
cheat-library/src/user/cheat/world/AutoChallenge.cpp

add bomb , dreamland spirit for auto challenge in sumeru

add item for auto challenge in sumeru

---

cheat-library/src/user/cheat/game/filters.cpp
cheat-library/src/user/cheat/world/AutoSeelie.cpp

merge from master to chinese

---

cheat-library/src/user/cheat/visuals/Browser.cpp
cheat-library/src/user/cheat/visuals/Browser.h

Browser is cool, but why 1:1
- Add slider to change the size of browser plane
- Add ability to change the size after the plane have been initialized

Add ability to change the width and height of browser

---

cheat-library/src/user/cheat/esp/ESP.cpp
cheat-library/src/user/cheat/game/filters.cpp

fix #570 
And fixed Paimon name display bug

Add "Aranara" for NPC filters

---

cheat-library/src/user/cheat/game/filters.cpp

ESP no longer marks the leaf on Nilotpala lotus

ESP Nilotpala lotus fix

---

cheat-library/src/user/cheat/player/GodMode.cpp
cheat-library/src/user/cheat/player/GodMode.h
cheat-library/src/user/cheat/player/RapidFire.cpp

Should solve multiple issues, especially #593.

RF alt, hooked to FireBeingHit instead of DoHitEntity.

---

cheat-library/src/user/cheat/visuals/TextureChanger.cpp
cheat-library/src/user/cheat/visuals/TextureChanger.h

Just a bunch of mess
- Add text to indicate the current Glider like with the Avatar
- Add texture change for glider (mix from [Ryujin](https://github.com/RyujinZX) Avatar Tex Change and [portra](https://github.com/portra400nc) ModelChanger)

Feature: Glider Texture Changer

---

cheat-library/src/user/cheat/imap/InteractiveMap.cpp

Scale map icons with font size

---

README.md
README_zh-Hans.md
README_zh-Hant.md

so I changed README a little bit

I moved "building" to the wiki

---

cheat-library/src/user/cheat/visuals/AnimationChanger.cpp
cheat-library/src/user/cheat/visuals/AnimationChanger.h

animationchanger delay

---

cheat-base/src/cheat-base/cheat/CheatManagerBase.cpp
cheat-base/src/cheat-base/cheat/misc/Settings.cpp
cheat-base/src/cheat-base/cheat/misc/Settings.h
cheat-base/src/cheat-base/render/renderer.cpp
cheat-base/src/cheat-base/util.cpp
cheat-library/src/user/cheat/teleport/CustomTeleports.cpp

Minor changes to themes.
Old format will automatically be converted into the new one.
It converted mine but make sure to create a backup.
Here's a few themes to test it out.
[themes.zip](https://github.com/Akebi-Group/Akebi-GC/files/9544487/themes.zip)
<details>
<summary>Preview</summary>
https://user-images.githubusercontent.com/78299538/189572081-68dcc397-9681-4c87-840b-54649a39ac29.mp4
</details>

Include styles in exported themes

---

cheat-library/src/user/cheat/player/RapidFire.cpp
cheat-library/src/user/cheat/player/RapidFire.h

* Make multi animation configurable
* Add configurable attack speed

Configurable multi-animation and attack speed

---

cheat-library/src/user/cheat/player/RapidFire.cpp

Fix attack speed module overriding game mechanics

---

cheat-library/src/appdata/il2cpp-functions.h
cheat-library/src/appdata/il2cpp-types.h
cheat-library/src/user/cheat/visuals/AnimationChanger.cpp

- Automatically gets the active character's animation list
TODO:

Improved Animation Changer

---

cheat-library/src/user/cheat/world/AutoSeelie.cpp

wah 
cant test as I dont have any seelie left
solve #703

Add LuminousSeelie to AutoSeelie.cpp

---

cheat-library/src/user/cheat/imap/InteractiveMap.cpp

Didn't touch the rest, because the Warning looks more appropriate

Changed 2 logs from WARNING to INFO
